### ISSUE TITLE
Url encoded request body not parsed

### ISSUE THREAD

**Issue by maxhov** [Azure/azure-functions-nodejs-worker#146]
#### Investigative information

Please provide the following:

- Timestamp: 2018-11-03T15:26:20.458
- Invocation ID: d38cce31-c3d2-49ff-b56a-3f595d5967c5
- Region: West-Europe

#### Repro steps

1. Generate a starter Function with Azure Core Function tools (2.1.725) with the following settings:
    1. `func init` -> select 2. node
    1. `func new` -> select 5. HTTP trigger -> choose default name (HttpTrigger)
    1. Add `context.log(req)` at the first line of the async function() to see the output of the req object in logging (see below in source).
    1. Deploy to Function App with WEBSITE_NODE_DEFAULT_VERSION=8.11.1 (default)
    1. Perform POST request on function, for instance with `curl -v "https://<func name>.azurewebsites.net/api/HttpTrigger?code=<code>" --data 'name=test'`

#### Expected behaviour

- After the POST request with body parameter 'name=test' included, I would expect that the Function would output 'Hello test'.

#### Actual behaviour

- 'req.body' equals 'name=test' as string instead of object. Therefor the if statement is evaluated as false.

#### Known workarounds

None

#### Related information 

* Programming language used:
Javascript

* Bindings used:
HTTP

* Tested and found not working with the following Node versions:
    - 8.11.1
    - 8.12.0
    - 10.13.0

<details>
<summary>Source</summary>

```javascript
module.exports = async function (context, req) {
    context.log(req)
    context.log('JavaScript HTTP trigger function processed a request.');

    if (req.query.name || (req.body && req.body.name)) {
        context.res = {
            // status: 200, /* Defaults to 200 */
            body: "Hello " + (req.query.name || req.body.name)
        };
    }
    else {
        context.res = {
            status: 400,
            body: "Please pass a name on the query string or in the request body"
        };
    }
};
```
</details>

**Comment by 0x6d6178** [comment]
So I looked into this a bit more and it seems that whenever you do a POST with a form (i.e. data is format as: "name=test&hobby=test", it is not parsed. However, when you make a JSON object of it (i.e. '{"name": "test"}', it will pick it up. I found that the way it is parsed in the function is unrelated to the content-type header set in the request (tested both with application/x-www-form-urlencoded). 

For me it is unclear in the documentation that the body needs to be submitted as a JSON object and that "normal" formatting (url encoding, not sure what the correct name would be) is not parsed correctly. Are there any plans to also support the url encoded format parsing? Another idea might be to update the documentation to clarify that a Function expects body parameters to be JSON formatted?

**Comment by mhoeger** [comment]
Yes, we don't automatically parse `application/x-www-form-urlencoded` data to JavaScript objects. We do automatically parse JSON objects of `application/json` content type (and if you don't want this automatic JSON parsing, you can leave off the content-type header or access the payload through `req.rawBody`).

I don't think we make this clear in documentation, but the assumption should be that automatic parsing is not done except in a few cases (like with JSON objects). We don't have plans on changing this, especially in major version 2 of functions because that would be a breaking change. Will address this gap in documentation though, thanks for pointing it out :) 

Another thing to note is that we do automagically parse query string parameters, so `curl -v "https://<func name>.azurewebsites.net/api/HttpTrigger?code=<code>&name=test"` will give you "Hello test", because test becomes the value of `req.query.name`.

**Comment by ejizba** [comment]
Closing in favor of https://github.com/Azure/azure-functions-nodejs-worker/issues/347
