### ISSUE TITLE
Provide a way to log metrics via context.log

### ISSUE THREAD

**Issue by jeffhollan** [Azure/azure-functions-nodejs-worker#147]
In C# you can use the [logger to create custom metrics](https://docs.microsoft.com/en-us/azure/azure-functions/functions-monitoring#logging-custom-metrics) in App Insights.  Would be nice to expose this as well - potentially with something like `context.log.metric('Duration', 1234)`

**Comment by mhoeger** [comment]
(Note: this feature is available in V1 but not V2)

**Comment by ejizba** [comment]
The link to the docs in the original issue is out of date, and I think by now all languages (except maybe C#Script?) are leveraging an app insights sdk as opposed to something on the logger. We have several improvements around app insights already on the docket, namely https://github.com/Azure/azure-functions-nodejs-worker/issues/522 and https://github.com/Azure/azure-functions-nodejs-worker/issues/523. Closing in favor of those and due to lack of activity on this issue
