### ISSUE TITLE
Warnings on context.log after context.done is called

### ISSUE THREAD

**Issue by mhoeger** [Azure/azure-functions-nodejs-worker#154]
It's very easy to mess up async patterns when using callbacks. We should emit a warning if we see any activity via context.log **after** context.done() has been called.

**Comment by jeffhollan** [comment]
Reviewing a support case where the problem was they were mixing async and callbacks and was causing code to not work as expected.  I think this may help but I'm wondering why it didn't work for them.  I know it's a larger problem, but wondering where this warning shows? In otherwords - if we emit this warning does it show in app insights traces? Kusto? The Portal?
