### ISSUE TITLE
access to node req/res objects

### ISSUE THREAD

**Issue by jpetitte** [Azure/azure-functions-nodejs-worker#173]
Can we access the native nodejs req/res objects? That would be extremely helpful for working with a number of libraries.

**Comment by jpetitte** [comment]
Understood. Just out of curiosity, what was the impetus for using a different req/res interface? Was it based on the shape of the req/res objects of the underlying code that runs the worker?

**Comment by mhoeger** [comment]
@jpetitte - the shape of the req object is based off of [this contract](https://github.com/Azure/azure-functions-language-worker-protobuf/blob/73896fd4bf1ec13183ad638e80e3d5a9c19c58cb/src/proto/FunctionRpc.proto#L362) for languages we support. This is what we use to turn an HTTP object for dotnet into a generic http object. We've added a few methods on req/res to be both "native http-like" and "express-like" since both are ways that developers would expect to interact with http objects.

**Comment by jpetitte** [comment]
Gotcha, that's what I suspected. Looks like I'll have to write a shim myself if I need it to be in the shape of Node's objects. Some people have already tried to adapt it to express specifically, https://github.com/yvele/azure-function-express, but it seems like there are a few compatibility issues with V2. 

Thanks for the info! You can close this one now unless you need it open.

**Comment by mhoeger** [comment]
Np - thanks John! Would love to take a look at what you come up with :)
