### ISSUE TITLE
Link to "uncaught exception recommendations" document on non-nodejs worker uncaught exceptions.

### ISSUE THREAD

**Issue by mhoeger** [Azure/azure-functions-nodejs-worker#180]
If user code throws an exception outside of the scope of function execution, it results in an uncaught exception.

Example:
```javascript
module.exports = function(context, req) {
  context.log("start", context.invocationId);
  setTimeout(function() { 
    var wrong = missing.var;
    context.log(wrong);
  }, 3000);
  context.log("ending!", context.invocationId);
  context.done();
}
```

Results in:
`[error] Worker ##### uncaught exception:  ReferenceError: missing is not defined.`

The root cause is usually confusion with async code. Although these errors should be minimized with: https://github.com/Azure/azure-functions-nodejs-worker/commit/e97f785607f06c5474d1a6dcaf576529eaca69db, it's worth considering if we want to make it a fatal exception [as it is currently](https://github.com/Azure/azure-functions-nodejs-worker/blob/6f87fce8a352ce2737ff4ab30eb51100269bf585/src/Worker.ts#L38-L41) (where we filter for exceptions that come from the language worker and treat all else as user code and not fatal).

cc: @pragnagopa

**Comment by mhoeger** [comment]
Per discussion with @fabiocav, it's dangerous and bad practice to not exit the node process on uncaught exception ([node docs](https://nodejs.org/docs/latest-v10.x/api/process.html#process_warning_using_uncaughtexception_correctly)). Instead, we should link to documentation that gives examples of common coding patterns / mistakes that would lead to this (async work not being scoped properly).

**Comment by thomas-mindruptive** [comment]
@mhoeger
I'm not sure if this is the right place to ask, but I'm hosting a nodejs/express app on azure which exits in spite of an "on uncaughtException" handler.
- node 10.15.2. 64 bit (I did the "languageWorkers:node:defaultExecutablePath" "trick" as well as add the path to the 64 bit node version to iisnode.yml)
-  gemlin javascript 3.4.0
- express 4.16.4

Problem: 

- nodejs gets killed in spite of "on uncaughtException" handler
- the reason is an exception in an async callback. The "open" function of a connection in  "gremlin/lib/driver/connection.js" installs an error handler which throws an `ECONNRESET` (caused by `TLSWrap.onread`) . The error handler in this "open" function is installed like this:  `this._ws.on('error', (err) => this._handleError(err))`. Since it happens asynchronously in the library (without any error callback or rejection), it's uncaught and I can't do anything about it. (I could uninstall all error listeners of the web-socket but that's probably bad.) I've also tried to add an error handler to the websocket (`._connection._connection._ws`). It didn't help either.
- Therefore I've implemented an "on uncaughtException" listener.

I've implemented the "on uncaughtException" listener for various reasons:

- My app is doing some scaffolding during startup, so it takes ~ 30 seconds to restart. 
- I'm the one who needs to decide if the process should be killed, not iisnode. If the error is well known and I know that the app doesn't get instable, it should continue running.
- For debugging/testing purposes I want to see/log all uncaught errors and not automatically restart the app.

The "on uncaughtException" handler works fine in our dev and test environments but it does not get fired on azure.

So I'd kindly ask if I'm doing something wrong or if it is true that iisnode kills node.exe in case of an uncaught error. And if it does, how does it know about it in spite of the "on uncaughtException" handler.

Any ideas are much appreciated, thanks a lot
Tom

**Comment by mhoeger** [comment]
@thomas-mindruptive - apologies about the delayedresponse! just to clarify - is this an nodejs/express app that is running on azure app service or azure functions?

**Comment by thomas-mindruptive** [comment]
@mhoeger - No prob, it's a nodejs/express app on azure app service. 
Best
