### ISSUE TITLE
Durable JS not working in Functions 3.0

### ISSUE THREAD

**Issue by cgillum** [Azure/azure-functions-nodejs-worker#276]
**Describe the bug**
When I run the sample orchestrations on Functions 3.0, they always complete immediately with a `null` output.

**Investigative information**

- Durable Functions extension version: 2.1.0
- durable-functions npm module version: 1.3.1
- Language (JavaScript/TypeScript) and version: JavaScript
- Node.js version: v10.14.1
- Functions runtime version: 3.0.2009

**To Reproduce**

1. Download the JS samples
2. Start the E1_HelloSequence orchestration

**Expected behavior**
The orchestration should finish and return the expected output.

**Actual behavior**
The orchestration finishes and returns a `null` output.

**Known workarounds**
Adding the following app setting works around the problem:
`"FUNCTIONS_V2_COMPATIBILITY_MODE": true`

**Additional context**

- Development environment (ex. Visual Studio): func.exe

**Comment by cgillum** [comment]
I’ve transferred this over because I believe this is as issue with the node worker. I debugged our extension’s custom trigger code and what I saw is that we no longer get function return values back unless we add the compatibility flag. We didn’t observe any such issue with .NET precompiled functions. I think trigger return values are a trigger feature only used by Durable Functions so it wouldn’t surprise me if this was broken without anyone realizing it.

FYI @fabiocav for triage

**Comment by fabiocav** [comment]
@mhoeger moving this to the current sprint because of the impact and upcoming changes to default to V3. 

Hoping this is something we can look at to see if we can include a fix with the next deployment, we can figure out the assignment once we better understand the problem.

**Comment by cgillum** [comment]
The following PR addresses this issue: https://github.com/Azure/azure-functions-nodejs-worker/issues/276

**Comment by fabiocav** [comment]
@mhoeger closing this as completed. Feel free to reopen if additional work is needed.

**Comment by virdeus** [comment]
I cannot verify if this works in other scenarios, but it does not work with version 3.0 in MS Learning. I am on Azure Developer Associate learning path and everything technologically has been fine until I started on the Durable module. Got a 500 error due to JSON issues. Essentially what has already been described. I did not save the stack however. I chose to switch to version 2.0 prior to googling for answers. It immediately fixed the issue. I am choosing to post not because it stops my learning path, since it now works using version 2.0, but to advise your team that it is still broken at least within the MS Learning context.

![image](https://user-images.githubusercontent.com/32570307/78055268-4e371780-7351-11ea-84ac-c339a5c36e4f.png)
