### ISSUE TITLE
Increase gRpc channel message size to int.MaxValue

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-nodejs-worker#287]
Related issue https://github.com/Azure/azure-functions-host/issues/5650

Need to set these values to int.MaxValue and ignore host settings.

**Comment by pragnagopa** [comment]
@mhoeger - can you please get this into this sprint?

**Comment by mhoeger** [comment]
Re-posting comment from host issue 5650:

After talking to @pragnagopa , if the grpc server on the functions-host side has a smaller max send/receive, this will be the bottleneck. This change is to make sure that clients are not sent a max message size that will be too large for them to safely handle. For JavaScript, a [number](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number) is defined has a maximum "safe" value (meaning arithmetic with the value will not be correct), but the maximum integer value is `1.7976931348623157e+308`. For my part, because the limit will always be constrained by the C# side, I'm going to close the Node.js issue because whatever the host sends will be a safe value.
