### ISSUE TITLE
Status (Result) code is always setting as 0 in function error (ex timer trigger function). how to set custom status code (like 400,404)

### ISSUE THREAD

**Issue by rishabhkumarjain** [Azure/azure-functions-nodejs-worker#391]
I want to know that how we can set result code in function (Timer Trigger) if any error generated in node js. Ex - If any error throw due to bad input, we want to log 400 status code.

#### Investigative information

NA

#### Expected behavior

Return Code should logged with the error stack for any function trigger.

Example:

 - I've created an timer trigger function, which is failing with invalid input. So in that case, want to throw exception with status 400. I've done all these but the exception are getting logged with only stackTrace and exception. No statusCode is getting log.

#### Actual behavior

Only exception and status code are getting logged, with out status code.

**Comment by ejizba** [comment]
Hi @rishabhkumarjain sorry for the delayed response. It's currently not possible to set the code and it was designed this way since a timer trigger is not a request. What exactly do you want to do with the result code and how will you use it in queries? For example - if you just want to know if the function failed, you can check the 'success' property for `true` or `false`.
