### ISSUE TITLE
Date toLocaleDateString produces incorrect locale format

### ISSUE THREAD

**Issue by hongzli** [Azure/azure-functions-nodejs-worker#400]
Specifying locale does not work correctly. This also impacts inline Javascript actions for Logic Apps Standard.

Code:
var text = new Date('12/25/2020').toLocaleDateString('en-CA');

Expected result - date in Canadian format (works in Node.js):
2020-12-25

Actual result - date in the US format:
12/25/2020

**Comment by AnatoliB** [comment]
I was unable to reproduce this: a simple Node.js 14 app on Windows gave me the expected result (2020-12-25). Please add more details on how exactly you are observing the wrong result:

- Node.js version
- OS
- Hosting plan details
- Entire repro app code

**Comment by hongzli** [comment]
This appears to repro only with NodeJS 12. I used a function app deployed to Azure on a Windows app service plan, consumption SKU. 

Result using NodeJS 12 (incorrect result):
![image](https://user-images.githubusercontent.com/69482556/127400662-728c46d5-cd43-4768-9266-00f167c4dda3.png)

Result using NodeJS 14 (desired, correct result):
![image](https://user-images.githubusercontent.com/69482556/127400824-153cd3f3-2ebf-4450-a843-c13957222e90.png)

Here is the code for the repro app:
```
module.exports = async function (context, req) {

    const responseMessage = new Date('12/25/2020').toLocaleDateString('en-CA');
    context.res = {
        // status: 200, /* Defaults to 200 */
        body: responseMessage
    };
}
```

Below are the settings for the app. Everything was left as default except for the NodeJS version:
![image](https://user-images.githubusercontent.com/69482556/127401155-e8b62eec-7458-4b3a-b7a0-d759063c22b2.png)

Resource ID of the app I used: /subscriptions/80d4fe69-c95b-4dd2-a938-9250f1c8ab03/resourceGroups/henryliujsdaterepro/providers/Microsoft.Web/sites/henryliujsdaterepro
Happy to make you a contributor to the app if that'd be helpful.

**Comment by AnatoliB** [comment]
I would highly recommend upgrading your app to Node.js 14 or looking for code workarounds. The chances of fixing this for Node.js 12 are slim because:

1. Even if it is technically possible to fix on the Functions side, this would be a breaking change potentially affecting existing apps. We can consider this breaking change for the next Functions runtime version (v4), but we cannot do that for the currently released runtime.
2. On the other hand, it is very probable that Functions v4 will not even support Node.js 12 to begin with.

**Comment by hongzli** [comment]
Ok thanks. Closing this issue with that workaround.
