### ISSUE TITLE
CVE-2020-7768 - Update grpc to newer version

### ISSUE THREAD

**Issue by briandunnington** [Azure/azure-functions-nodejs-worker#407]
This was originally filed as Azure/azure-functions-core-tools#2594 but it was closed due to author inactivity. But the azure-functions-core-tools package was never updated so we are still getting flagged for this. Can you publish a new version with the updated dependency? (We are using v3) 
![image](https://user-images.githubusercontent.com/1545776/125021816-39573280-e030-11eb-9c38-bb05c4e75917.png)

**Comment by apawast** [comment]
@AnatoliB could help take a look at this?

**Comment by ejizba** [comment]
This was fixed in the worker in https://github.com/Azure/azure-functions-nodejs-worker/pull/380 and released in [v2.1.2](https://github.com/Azure/azure-functions-nodejs-worker/releases/tag/v2.1.2)

Which was updated in the cli in https://github.com/Azure/azure-functions-core-tools/pull/2661 and released in [v3.0.3734](https://github.com/Azure/azure-functions-core-tools/releases/tag/3.0.3734)
