### ISSUE TITLE
Support for Node 16 LTS

### ISSUE THREAD

**Issue by chuanqisun** [Azure/azure-functions-nodejs-worker#455]
Node 14 LTS has entered maintenance and 16 LTS is now active. [See schedule](https://nodejs.org/en/about/releases/) 

However, the support table shows that javascript runtime v3 and even v4 preview both only support up to node 14. I wonder if this is intentional or a miscommunication. [See support matrix](https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-node?tabs=v2#node-version)

Please consider support node 16. This will be very helpful for teams using npm workspaces for a mono repo setup. Currently, our team is blocked from adopting mono repo because the node 14 package manager cannot handle workspaces.

**Comment by ejizba** [comment]
Hi @chuanqisun support for Node 16 is in the works for v4. See the new support matrix which is documented here:
https://github.com/Azure/Azure-Functions/issues/1999. That issue is tracking updates to the official docs as well.

You should be able to try out Node 16 in Azure if you follow [these instructions](https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-node?tabs=v2#setting-the-node-version) to update the version on a v4 app (even though 16 is not listed there yet). You can also try locally if you're on at least core tools version 4.0.3928. Of course this is all still in preview.

**Comment by ejizba** [comment]
FYI - support for Node.js 16 is officially in public preview 🎉 

https://azure.microsoft.com/updates/public-preview-nodejs-16-in-azure-functions/

**Comment by chuanqisun** [comment]
Thanks!
