### ISSUE TITLE
Support Node 16

### ISSUE THREAD

**Issue by kristoffer-zliide** [Azure/azure-functions-nodejs-worker#566]
Initial release: 2021-04-20 - over 11 months ago
Active LTS start: 2021-10-26

https://nodejs.org/en/about/releases/

It has been in "preview" for over four months: https://azure.microsoft.com/en-us/updates/public-preview-nodejs-16-in-azure-functions/.

**Comment by ejizba** [comment]
Hi @kristoffer-zliide, you will see an announcement regarding Node 16 _very soon_. I share your frustration with how long it took, and I plan to ensure the team does much better with Node 18 which is why I created the issue for it yesterday.

Previously [this](https://github.com/Azure/azure-functions-nodejs-worker/issues/455) was the only issue we had tracking Node 16 support, but it was closed when public preview was announced. I'll leave your issue open until we announce GA.

**Comment by kristoffer-zliide** [comment]
Very soon, indeed: https://azure.microsoft.com/en-us/updates/generally-available-nodejs-16-in-azure-functions-2/ 😄 Thanks!

**Comment by ejizba** [comment]
No problem!

Just fyi, you may continue seeing a "Preview" label in the portal and VS Code until [this change](https://github.com/Azure/azure-functions-ux/pull/6589) rolls out (could take a few weeks). Regardless, the announcement trumps those UI labels
