### ISSUE TITLE
Version 3.5.0 of the npm package is not appearing in NPM repository

### ISSUE THREAD

**Issue by timtucker-dte** [Azure/azure-functions-nodejs-worker#627]
Version 3.5.0 of the npm package is not appearing in NPM repository

#### Repro steps
Follow instructions from:
https://github.com/Azure/azure-functions-nodejs-library/blob/v3.x/README.md

i.e., run:
npm install @azure/functions

then start using version 3.5.0

#### Expected behavior
Version 3.5.0 is installed

#### Actual behavior
Version 3.2.0 is installed

NPMjs.com registry shows the package as updated 5 days ago, but still shows 3.2.0 as the latest version:
https://www.npmjs.com/package/@azure/functions

**Comment by ejizba** [comment]
Hi @timtucker-dte that's because 3.5.0 is still a preview version (3.5.0-alpha.3). You can explicitly install it with `npm install @azure/functions@next` if you want to try it out. However there's a few caveats
- There's a small chance we need to make a breaking change before we mark it non preview
- It doesn't actually work in Azure yet. We describe 3.5.0 as the first version where "you can override the default shipped in Azure with the below steps." However, that is not possible until the other half of this work rolls out in Azure with Host v4.12.0

**Comment by timtucker-dte** [comment]
Ah -- missed the extra detail on the versions page from NPM.

Seems confusing that the version #'s on the GitHub releases page don't align with the NPM version #'s, though -- on most other projects I'm used to seeing them be in sync (so if the NPM version was tagged alpha the GitHub release version would also be tagged as alpha).

Is there a reason why the GitHub release just shows up as "3.5.0" and not "3.5.0-alpha.3"?

**Comment by ejizba** [comment]
Yes it's a bit confusing as this is a pretty big transition for us. There are two separate pieces that currently have the same version (3.5.0) because we literally just split them, but moving forward will diverge in their versions. The "worker" (this repo) ships in Azure. The "library" (a separate repo [here](https://github.com/Azure/azure-functions-nodejs-library)) ships on NPM. The library repo does not have any GitHub releases yet, and I had planned to make the first one for 3.5.0 as soon as we publish the non-preview package

**Comment by jamiehaywood** [comment]
with `3.5.2` released and the Azure Function Host now updated to `4.15.0` https://github.com/Azure/azure-functions-host/releases/tag/v4.15.0 - does this mean we can use the new function model (sans `host.json`)?

**Comment by ejizba** [comment]
Sorry for the delay - the necessary changes in Azure just finished rolling out, so I have published v3.5.0 of the npm package. Release notes here: https://github.com/Azure/azure-functions-nodejs-library/releases/tag/v3.5.0

@jamiehaywood I responded to your questions here: https://github.com/ejizba/func-nodejs-prototype/issues/19#issuecomment-1338339678
